# Generated by Django 4.1.1 on 2022-09-21 18:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_automodel_is_active_brand_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='next_date',
            field=models.DateField(default=app.models.expiration),
        ),
    ]
