# Generated by Django 4.1.1 on 2022-09-21 18:25

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_maintenance_next_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='next_date',
            field=models.DateField(default=app.models.expiration, null=True),
        ),
    ]
