# Generated by Django 4.1.1 on 2022-09-21 18:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_maintenance_next_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='next_date',
            field=models.DateField(auto_created=True, default=app.models.expiration),
        ),
    ]
