# Generated by Django 4.1.1 on 2022-09-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_maintenance_next_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
