# Generated by Django 4.1.1 on 2022-09-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_maintenance_is_started_alter_vehicle_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='automodel',
            name='type',
            field=models.CharField(choices=[('Combustion', 'Combustion'), ('Eletric', 'Eletric'), ('Manual', 'Manual')], default='', max_length=10),
        ),
    ]
