# Generated by Django 4.1.1 on 2022-09-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_automodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automodel',
            name='type',
            field=models.CharField(choices=[('Combustion', 'Combustion'), ('Electric', 'Electric'), ('Manual', 'Manual')], default='', max_length=10),
        ),
    ]
