# Generated by Django 4.1.1 on 2022-11-19 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_maintenance_km_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance",
            name="vehicle",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.vehicle"
            ),
        ),
    ]
